<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AxetosOS.Products.NES.VirtualHardware\AxetosOS.Products.NES.VirtualHardware.csproj" />
    <ProjectReference Include="..\AxetosOS.Products.NES.Host.Windows\AxetosOS.Products.NES.Host.Windows.csproj" />
  </ItemGroup>
</Project>
