<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AxetosOS.Products.NES.VirtualHardware\AxetosOS.Products.NES.VirtualHardware.csproj" />
    <ProjectReference Include="..\..\..\..\..\AxetosOS.Audio.Abstractions\AxetosOS.Audio.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\..\AxetosOS.Audio.Windows\AxetosOS.Audio.Windows.csproj" />
    <ProjectReference Include="..\..\..\..\..\AxetosOS.Rendering.Abstractions\AxetosOS.Rendering.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\..\..\AxetosOS.Rendering.Windows\AxetosOS.Rendering.Windows.csproj" />
  </ItemGroup>
</Project>
